server:
  port: 8080

#Springboot2.6后 SpringMVC 处理映射匹配的默认策略已从AntPathMatcher变为PathPatternParser。修改配置否则swagger启动报错
spring:
  profiles:
    active: dev
  application:
    name: grpc-client
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # nacos注册中心
      config:
        namespace: 8075b407-5a14-412d-9aeb-6db9b3ff57d5
      discovery:
        namespace: 8075b407-5a14-412d-9aeb-6db9b3ff57d5
        group: DEFAULT_GROUP
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


grpc:
    client:
      # gRPC的服务端名单@GrpcClient注解中会用到
      mygrpc-server:
        address: 'static://localhost:9093'
        enableKeepAlive: true
        keepAliveWithoutCalls: true
        negotiationType: plaintext

